### ISSUE TITLE
komisje_obwodowe-szablon.csv

### ISSUE THREAD

**Issue by ghost** [adamkowalewski/OtwartaPlatformaWyborcza#13]
@adamkowalewski 
Zastanawiam się nad poprawnością nagłówków.
- `okregowaId[1-51]` - czy `[1-51]` powinno tam być?
- `obwodTyp` - nie powinno być `typObwodu` albo `obwodType`?

**Comment by adamkowalewski** [comment]
1. Tak! Oficjalna lista 51 Komisji Okręgowych została już ogłoszona. 
   - [PKW Uchwała z dnia 9 marca 2015](http://pkw.gov.pl/uchwaly-panstwowej-komisji-wyborczej-prezydent/uchwala-panstwowej-komisji-wyborczej-z-dnia-9-marca-2015-r-w-sprawie-powolania-okregowych-komisji-wyborczych-w-celu-przeprowadzenia-wyborow-prezydenta-rzeczypospolitej-polskiej-zarzadzonych-na-dzien-10-maja-2015-r.html)
   - [PKW Uchwała z dnia 26 stycznia 2015](http://prezydent2015.pkw.gov.pl/akty_prawne/0/53_UCHWALA__PANSTWOWEJ_KOMISJI_WYBORCZEJ__z_dnia_26_stycznia_2015_r__w_sprawie_okreslenia_wlasciwosci_miejscowej_numerow_oraz_siedzib_okregowych_komisji_wyborczych_w_wyborach_Prezydenta_Rzeczypospolitej_Polskiej_w_2015_r)
     Podczas nadchodzących wyborów Prezydenta RP 2015 będzie dokładnie 51 Komisji Okręgowych. 
2. Ten dokument to draft - celem jest definicja formatu który przekażemy PKW w ramach oficjalnego pisma o udostępnienie list 27 000+ Komisji Obwodowych.
